// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vcl.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - VclRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface VclRoot : GPBRootObject
@end

#pragma mark - EncodedOwnerSecret

typedef GPB_ENUM(EncodedOwnerSecret_FieldNumber) {
  EncodedOwnerSecret_FieldNumber_CreditValue = 1,
  EncodedOwnerSecret_FieldNumber_SecretBlinding = 2,
};

/**
 * Encoded data to represent a owner secret used by VCL solution.
 **/
@interface EncodedOwnerSecret : GPBMessage

@property(nonatomic, readwrite) int64_t creditValue;

@property(nonatomic, readwrite, copy, null_resettable) NSString *secretBlinding;

@end

#pragma mark - EncodedConfidentialCredit

typedef GPB_ENUM(EncodedConfidentialCredit_FieldNumber) {
  EncodedConfidentialCredit_FieldNumber_Point = 1,
};

/**
 * Encoded data to represent a confidential credit used by VCL solution.
 **/
@interface EncodedConfidentialCredit : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *point;

@end

#pragma mark - VclResult

typedef GPB_ENUM(VclResult_FieldNumber) {
  VclResult_FieldNumber_Credit = 1,
  VclResult_FieldNumber_Secret = 2,
  VclResult_FieldNumber_Proof = 3,
};

/**
 * Return data to FFI C interface
 **/
@interface VclResult : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *credit;

@property(nonatomic, readwrite, copy, null_resettable) NSString *secret;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proof;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
