# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'WedprDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WedprDemo
  # pod 'SwiftProtobuf', '~> 1.0'
  pod "Protobuf",' ~> 3.11.3'
  # :git => "https://github.com/google/protobuf.git"

end
